apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    method: fromcode
    etiqueta: ejemplo_de_etiqueta
    etiqueta: 1_etiqueta
    run: temp-yaml
  name: temp-yaml
spec:
  containers:
  - image: nginx
    name: temp-yaml
